### ISSUE TITLE
FID is not working on Sitecore CMS sites

### ISSUE THREAD

**Issue by msage-godaddy** [cmorten/cypress-web-vitals#4]
# Issue

Setup:

- node version: 16.3
- cypress-web-vitals version: "cypress-web-vitals": "^0.4.0",

## Details

>We are trying to run vitals on taylormorrison.com, godaddy.com and sitecore.com - all 3 sites cannot return FID value. GoDaddy & SiteCore both skip it, TaylorMorrison throws and injection error.

## Side note

> Can you update your dependencies to include Cypress ^9

**Comment by cmorten** [comment]
Hi @msage-godaddy! Do you have some example URLs which could used to test against to work out what’s going on?

Do you have the stack trace of the injection error you are seeing?

**Comment by msage-godaddy** [comment]
See screenshots :) 
TaylorMorrison.com throws the error so I can get a stack trace. The other two just skip.
And SUPER odd, the inject script is doing funky things above the header

<img width="1417" alt="Screen Shot 2022-03-31 at 8 02 18 AM" src="https://user-images.githubusercontent.com/31971850/161087748-884bc2d2-ee17-43a3-9eff-e77544806830.png">
<img width="1435" alt="Screen Shot 2022-03-31 at 8 03 58 AM" src="https://user-images.githubusercontent.com/31971850/161087790-6d2f4bac-f781-4c45-a1c0-c6c954f5a224.png">
<img width="1423" alt="Screen Shot 2022-03-31 at 8 03 29 AM" src="https://user-images.githubusercontent.com/31971850/161087777-9345ed62-60af-4fcb-a3f8-6b2c2cb5fcba.png">

**Comment by cmorten** [comment]
Looks like some of the regex hackery to intercept the response and inject the script needs some work.

Curious with the body not being defined or something such that it can’t even run string methods (i.e. replace).

Hunch is hitting some 304 / local memory cache like scenarios which Cypress doesn’t handle OOTB particularly well, but will try have a dig around to see for sure

**Comment by cmorten** [comment]
Ah interesting - suggestion (if couldn't make any ground) would have been to explore `cypres-audit` for it's lighthouse integration which I've had a lot of success with.

Not going to get far with godaddy.com - I'm getting 403s immediately so their WAF clearly not happy with some part of my setup.

taylormorrision.com is interesting, some sort of multipart form request kicks off resulting in the error - should be mitigated by limiting the request interceptor for the script injection to the _first GET_ request on the domain, rather than anything subsequent.

Will keep looking

**Comment by msage-godaddy** [comment]
> Curious with the body not being defined or something such that it can’t even run string methods (i.e. replace).
> 
> ... but perhaps for the best to be consistently simulating a cold visitor rather than a mix depending on whether your first run warmed up the cache), but will try have a dig around to see for sure.

I did try a few 'warm up' type things ... had a before statement that visited the url first, used the cy.visit in the test block itself before calling cy.vitals({thresholds:metrics}), and also a cy.vitals({thresholds:metrics, url:sameUrl})

So my test would look something like:
it('reports vitals', () => {
  cy.visit("https://www.sitecore.com");
  cy.vitals({thresholds:metrics, url:"https://www.sitecore.com"})
  }
  
  where the thresholds is  the normal metrics from your examples.
  
  & Yes, the GoDaddy WAF is going to block you unless you're internal, which is why I gave you the other two ;)

**Comment by cmorten** [comment]
Have observed greater success when don't rely on the default selector for driving FID, but instead provide a custom selector specific to the page, e.g.

```js
describe("cy.vitals()", () => {
  beforeEach(() => {
    cy.visit("https://www.taylormorrison.com/");
  });

  it("should meet the web-vitals default thresholds", () => {
    cy.vitals({ firstInputSelector: ".l-header__inner" });
  });
});
```

Need to dig further into what triggers a FID in Chrome - not sure if the 5 clicks the lib does currently are just happening "too early" so hit before the site is responsive... perhaps needs to be something that runs in background with user configurable timeout (so don't wait forever...)

**Comment by cmorten** [comment]
Ah the Tyler Morrison thing is fixed in https://github.com/cmorten/cypress-web-vitals/pull/7

**Comment by msage-godaddy** [comment]
Interesting, I just submitted a PR for #4, just adding toString() on the res

**Comment by msage-godaddy** [comment]
Ugh, maybe not, I had temporary success then gone again. I'll pull from latest and see if your latest did some magic.

**Comment by msage-godaddy** [comment]
Much better, getting results! Still seeing the odd funkiness with the script at the top of the page, and I don't know if that's affecting our numbers? When I do some straight string replacement the numbers are similar, so maybe not.

<img width="1682" alt="Screen Shot 2022-03-31 at 3 59 19 PM" src="https://user-images.githubusercontent.com/31971850/161163944-a76bec7e-de5b-4205-aada-e1cbfa5b34ac.png">
<img width="2021" alt="Screen Shot 2022-03-31 at 4 02 28 PM" src="https://user-images.githubusercontent.com/31971850/161163950-8cd70401-7044-46e5-9925-6b39b37a96aa.png">

Thank you so much for your dedicated time on this! We appreciate it greatly!

**Comment by cmorten** [comment]
> Much better, getting results! Still seeing the odd funkiness with the script at the top of the page, and I don't know if that's affecting our numbers? When I do some straight string replacement the numbers are similar, so maybe not.
> 
> <img alt="Screen Shot 2022-03-31 at 3 59 19 PM" width="1682" src="https://user-images.githubusercontent.com/31971850/161163944-a76bec7e-de5b-4205-aada-e1cbfa5b34ac.png">
> 
> <img alt="Screen Shot 2022-03-31 at 4 02 28 PM" width="2000" src="https://user-images.githubusercontent.com/31971850/161163950-8cd70401-7044-46e5-9925-6b39b37a96aa.png">
> 
> Thank you so much for your dedicated time on this! We appreciate it greatly!

Hmm strange - definitely only see this when using this lib (doesn’t show on a plain cy.visit())?

Displayed markup as text feels like the regex matcher for the head tag playing up. Limited in how much can investigate… but perhaps will just download the godaddy page and serve locally to try repro and fix.

**Comment by cmorten** [comment]
Perhaps following as you have done and reaching for the end of the head is the simplest solution… I think originally I was concerned with ensure the script was available asap this the top of the head, but these metrics (other than TTFB) all relate to concerns of the body, so there’s no risk of missing a marker so long as the vitals script is somewhere in the head.

Should probably embed the web vitals script directly over doing an import - static parsing will no doubt trump a network roundtrip (unless cypress has a handy way of getting it into the browser cache beforehand)

**Comment by msage-godaddy** [comment]
Every other major site I test doesn't have this problem. The odd scripting at the top of our pages might not anything to do with your code. Every other major site I test does. not have this problem. Beside's, we're using this for internal monitoring and trending, more than for customer metrics. This just allows us to see, in a vacuum, that nothing is changing or breaking. I consider this issue resolved, and again, huge gratitude for working on this so quickly! <3

**Comment by cmorten** [comment]
@msage-godaddy think I've solved the issue with the erroneous text. Check out `cypress-web-vitals@1.0.0`.

**Comment by msage-godaddy** [comment]
Perfection! and *FAST* Way to go!  Thank you so much!
